### ISSUE TITLE
Aufhänger unter Verechnung bei Konsultation

### ISSUE THREAD

**Issue by tecalto** [elexis/elexis#10]
Elexis unter OS X hängt sich bei mir auf, wenn man unter Verechnung bei Konsultation auf einen Eintrag klickt und danach unten ins leere Feld.

**Comment by col-panic** [comment]
Ich kann das gerade mit dem aktuellen master nicht nachvollziehen. Welche Version verwendest du? Könntest du bitte einen Screenshot machen mit den Clickpunkten markiert? anke

**Comment by tecalto** [comment]
Ist bei mir mit Version 3.4 und 3.5.
![clickpunkte](https://user-images.githubusercontent.com/16159319/38853045-53a182a4-421c-11e8-980a-24d69a1ab564.png)

**Comment by col-panic** [comment]
Ich kann das noch nicht nachvollziehen; wie wurden denn die Leistungen hinzugefügt?

**Comment by tecalto** [comment]
Auf Verrechnung klicken. Dann aus Leistungen diese hinzugefügt.

**Comment by tecalto** [comment]
Mit Version 3.6 ist dieses Problem nun bei mir behoben.
