### ISSUE TITLE
Sprache

### ISSUE THREAD

**Issue by ArSa-Apps** [elexis/elexis#8]
Feature: Gäbe es die Möglichkeit, die Texte der Oberfläche mit einer anderen Sprache zu ersetzen? Wie z.B. mit Englisch oder Französisch usw...

**Comment by col-panic** [comment]
Hey Niklaus, kannst du darauf bitte eingehen? Danke

**Comment by ngiger** [comment]
Elexis ist prinzipiell übersetzbar. Es gab mal einen Arzt in Yverdon, der mit einer französischen Version gearbeitet hatte.
In den nächsten Monaten ist geplant der Master-Branch so anzupassen, dass auch eine Italienische-Übersetzung hinzukommen kann.
Für einen Einsatz in einem Land ausserhalb der Schweiz müssten jedoch zusätzlich Anpassungen für Abrechnungssysteme, Medikamente, etc gemacht werden, was einigen Aufwand bedeutet.
Weiter gibt es innerhalb von Elexis aus historischen Gründen Code-Konstanten, z.B. 'm' für männlich und 'w' für weiblich, welche Anpassungen am Code erfordern.
Werde innerhalb von 7 Tagen schon gemachte Arbeiten und Gedanken unter wiki.elexis.info dokumentieren und hier darauf verlinken.
Mitstreiter für weitere Sprachen sind hochwillkommen. Ich gebe gerne auch Auskünfte per Telefon +41 55 612 20 54.

**Comment by ngiger** [comment]
Please have a look at https://wiki.elexis.info/Translation. Feedback is highly welcomed.
